name: Proferotech
markdown: redcarpet
pygments: true
paginate: 1000
exclude: ['sass', 'node_modules', '.gitignore', 'config.rb', 'gruntfile.js', 'gzip.rb', 'package.json', 'README.md', 'design', '.sass-cache', 'js/lib']
permalink: /:categories/:title